-- DROP TABLES
DROP TABLE IF EXISTS verification_codes CASCADE;
DROP TABLE IF EXISTS product_pricings CASCADE;

DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;

DROP TABLE IF EXISTS product_moderation CASCADE;
DROP TABLE IF EXISTS product_complaint CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS product_reviews CASCADE;
DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS buyer_moderation CASCADE;
DROP TABLE IF EXISTS buyers CASCADE;

DROP TABLE IF EXISTS seller_moderation CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;

DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- DROP TYPES

DROP TYPE IF EXISTS product_complaint_status;
DROP TYPE IF EXISTS verification_type;
DROP TYPE IF EXISTS unit_enum;
