CREATE TABLE outbox (
	id UUID PRIMARY KEY,
	type TEXT NOT NULL,
	payload JSONB NOT NULL,
	occurred_at TIMESTAMPTZ NOT NULL,
	processed_at TIMESTAMPTZ
);

CREATE TABLE accounts (
	id UUID PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	banned_at TIMESTAMPTZ
);

CREATE TYPE verification_type AS ENUM (
	'BUYER_VERIFY',
	'SELLER_VERIFY',
	'EMAIL_CHANGE',
	'PASSWORD_RESET'
);

CREATE TABLE verification_codes (
	id UUID PRIMARY KEY,
	account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
	code VARCHAR(6) NOT NULL,
	type verification_type NOT NULL,
	expires_at TIMESTAMPTZ NOT NULL,
	used_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

	UNIQUE (account_id, type)
);

-- Do some stuff here
CREATE TABLE admins (
	id UUID PRIMARY KEY REFERENCES accounts(id),
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL
);

CREATE TABLE sellers (
	id UUID PRIMARY KEY REFERENCES accounts(id),

	store_name VARCHAR(256) NOT NULL,
	store_slug VARCHAR(256) UNIQUE NOT NULL,
	description TEXT,
	rating NUMERIC(2,1) CHECK (rating BETWEEN 0 AND 5),

	total_sales BIGINT NOT NULL DEFAULT 0,

	is_verified BOOLEAN NOT NULL DEFAULT FALSE,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,

	support_email VARCHAR(255),
	support_phone VARCHAR(32),

	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE seller_moderation (
	id UUID PRIMARY KEY,
	seller_id UUID NOT NULL REFERENCES sellers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	admin_id UUID REFERENCES admins(id) ON DELETE SET NULL ON UPDATE CASCADE,
	action_type VARCHAR(20) NOT NULL,
	reason TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE buyers (
	id UUID PRIMARY KEY REFERENCES accounts(id),
	username VARCHAR(256) NOT NULL,

	is_verified BOOLEAN NOT NULL DEFAULT FALSE,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,

	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE buyer_moderation (
	id UUID PRIMARY KEY,
	buyer_id UUID NOT NULL REFERENCES buyers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	admin_id UUID REFERENCES admins(id) ON DELETE SET NULL ON UPDATE CASCADE,
	action_type VARCHAR(20) NOT NULL,
	reason TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE products (
	id UUID PRIMARY KEY,
	seller_id UUID NOT NULL REFERENCES sellers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	name VARCHAR(255) NOT NULL,
	description TEXT,
	stock_quantity NUMERIC(10,3) NOT NULL CHECK(stock_quantity >= 0),
	base_unit VARCHAR(10) NOT NULL,
	rating NUMERIC(2,1) CHECK (rating BETWEEN 0 AND 5),
	status VARCHAR(20) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	deleted_at TIMESTAMPTZ
);

CREATE TABLE product_sell_units (
	id UUID PRIMARY KEY,
	product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	unit VARCHAR(10) NOT NULL,
	conversion_factor NUMERIC(10,3) NOT NULL CHECK (conversion_factor > 0),
	UNIQUE (product_id, unit)
);

CREATE TABLE product_reviews (
	id UUID PRIMARY KEY,
	buyer_id UUID NOT NULL REFERENCES buyers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	rating NUMERIC(2,1) NOT NULL CHECK (rating BETWEEN 0 AND 5),
	content TEXT,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE product_images (
	id UUID PRIMARY KEY,
	product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	url TEXT NOT NULL,
	position SMALLINT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL
);

CREATE TYPE product_complaint_status AS ENUM (
	'CONFIRMED',
	'DISMISSED',
	'PENDING'
);

CREATE TABLE product_complaint (
	id UUID PRIMARY KEY,
	buyer_id UUID NOT NULL REFERENCES buyers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	admin_id UUID REFERENCES admins(id) ON DELETE SET NULL ON UPDATE CASCADE,
	subject VARCHAR(100) NOT NULL,
	details TEXT NOT NULL,
	status product_complaint_status NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE product_moderation (
	id UUID PRIMARY KEY,
	product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	admin_id UUID REFERENCES admins(id) ON DELETE SET NULL ON UPDATE CASCADE,
	product_complaint_id UUID REFERENCES product_complaint(id) ON DELETE SET NULL ON UPDATE CASCADE,
	action_type VARCHAR(30) NOT NULL,
	reason TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE carts (
	id UUID PRIMARY KEY REFERENCES buyers(id),
	shipping_address_id UUID,
	status VARCHAR(20) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cart_items (
	id UUID PRIMARY KEY,
	cart_id UUID NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
	product_id UUID NOT NULL REFERENCES products(id),
	quantity NUMERIC(10,3) NOT NULL CHECK(quantity > 0),
	sell_unit VARCHAR(10) NOT NULL
);

CREATE TABLE orders (
	id UUID PRIMARY KEY,
	buyer_id UUID NOT NULL REFERENCES buyers(id)  ON DELETE CASCADE,
	seller_id UUID NOT NULL REFERENCES sellers(id) ON DELETE SET NULL ON UPDATE CASCADE,
	total_price NUMERIC(12,2) NOT NULL,
	status VARCHAR(32) NOT NULL,
	payment_method VARCHAR(32) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	cancelled_at TIMESTAMPTZ
);

CREATE TABLE order_items (
	id UUID PRIMARY KEY,
	order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
	product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	quantity NUMERIC(10,3) NOT NULL CHECK(quantity > 0),
	price_at_purchase NUMERIC(12,2) NOT NULL,
	sell_unit VARCHAR(10) NOT NULL
);
